version: "3.8"

services:
  products:
    build: ./products
    container_name: products_service
    ports:
      - "5001:5001"

  orders:
    build: ./orders
    container_name: orders_service
    ports:
      - "5002:5002"

  payments:
    build: ./payments
    container_name: payments_service
    ports:
      - "5003:5003"

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - products
      - orders
      - payments
